-- Migration 024: Add dynamic course fields
-- Up

ALTER TABLE courses
ADD COLUMN IF NOT EXISTS badges JSONB,
ADD COLUMN IF NOT EXISTS quick_stats JSONB,
ADD COLUMN IF NOT EXISTS included TEXT[],
ADD COLUMN IF NOT EXISTS overview JSONB,
ADD COLUMN IF NOT EXISTS syllabus JSONB,
ADD COLUMN IF NOT EXISTS related_courses UUID[],
ADD COLUMN IF NOT EXISTS deposit DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS reviews_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 0.00;
